services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      - discovery-service
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - '8085:8085'
    expose:
      - '8085'
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8087:8087'
    expose:
      - '8087'
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8087/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - '8086:8086'
    expose:
      - '8086'
    depends_on:
      customer-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:9999/
  ecom-app-angular:
    build: ./ecom-app-angular
    container_name: ecom-app-angular
    ports:
      - '82:80'
    expose:
      - '82'



